### PR TITLE
Add argument and jq processing to d shell script

### PR DESCRIPTION
**Pull request by iainsimmons**
This adds an argument to your 'd' shell script that runs `npm run dev` / `yarn dev` / `pnpm dev` etc so that you can also run other package.json scripts (like build or test).

It uses `jq` to get the first key in `scripts` that _starts_ with the passed in argument. If not provided or if there is no match, it falls back to `dev`.

I thought of this because I have an old Gatsby project that uses `yarn develop` and I always forget.

### CODE REVIEW

**Comment by iainsimmons** [comment]
Sorry for all the extra commits, I made the mistake of trying to edit this on GitHub! Also my local copy is very slightly different because I don't use the tmux rename bit (I just run things like this in another pane in the same window).

It would probably be good to squash all of these commits if you decide to merge them.

**Comment by joshmedeski** [comment]
Hey @iainsimmons, I like this idea!

However, I always use `d` for the dev script ("d is for dev" in my mind). What do you think of adding this kind of functionality to a "r" script? (r is for run, i.e. pnpm run {script}).

**Comment by joshmedeski** [comment]
I went ahead and merged it! I'll play around with it and let you know if I find it helpful.

**Comment by iainsimmons** [comment]
> Hey @iainsimmons, I like this idea!
> 
> However, I always use `d` for the dev script ("d is for dev" in my mind). What do you think of adding this kind of functionality to a "r" script? (r is for run, i.e. pnpm run {script}).

Hi Josh,

Sorry for the slow response, my wife and I just bought our first home and we're in the middle of renovations! ☺️

Thanks for merging!

Yeah I did think about whether `d` was still the most appropriate, but didn't want to mess with your muscle memory/pneumonic.

I used to use [Anthony Fu's ni](https://github.com/antfu/ni) for this, which has different commands for install, run, uninstall, exec, etc. That would obviously be a much bigger thing, so I was mainly going for a simpler addition to what you had that would cover just a few more edge cases, but also only rely on shell scripts or other CLIs like jq (ni uses Node and parses the package.json file).

Again, thanks for merging it anyways, but of course feel free to modify to suit your needs.

Cheers,
iain

**Pull request merged**
