### PR TITLE
Merge in latest fork updates

### PR DESCRIPTION
**Pull request by jdhoffa**

### CODE REVIEW

**Comment by jdhoffa** [comment]
Oops got my streams crossed, sorry about that!!

**Comment by joshmedeski** [comment]
All good, feel free to leave any feedback. I just rewrote all of my neovim setup with the native LSP and lua!

**Comment by jdhoffa** [comment]
Yeah absolutely!! I'm still just getting it all up and running honestly, and getting used to your defaults (also trying to wrap my head around packer/ lua ;-D)

but once i'm comfortable with it all I'll def be opening some issues :-)

**Comment by jdhoffa** [comment]
Also this is some really incredible work!! I've been slowly trying to migrate towards a fully tmux/vim based stack for a little while, and this really feels intuitive.

**Comment by joshmedeski** [comment]
Welcome to the club. There's still more work for me to do with the LSP, so feel free to track the repo for changes.

**Comment by jdhoffa** [comment]
I will absolutely!! I don't know much about LSP, I'm definitely still a bit of a noob with this, but if you open issues for anything you are/ want to work on, I'll def try to hack away a bit :-)

(I saw what's on the README too, will see if there's anything i can tackle)

**Pull request closed without merging**
